PAIRS = [
    "EURUSD", "GBPUSD", "USDJPY", "USDCHF", "AUDUSD",
    "NZDUSD", "USDCAD", "EURGBP", "EURJPY", "GBPJPY",
    "AUDJPY", "EURAUD", "EURCHF", "GBPCHF", "CADJPY",
    "NZDJPY", "EURCAD", "GBPAUD", "GBPCAD", "AUDCAD"
]

RANGE_MIN_PIPS = 20
RANGE_MAX_PIPS = 30
MAX_ACTIVE_SETUPS = 5

FIBO_ENTRY = 0.786
FIBO_SL = 1.0

TP1_RR = 2.0
TP2_RR = 4.0

BACKTEST_START = "2023-01-01"
BACKTEST_END = "2024-12-31"
